### ISSUE TITLE
Refactor unsigned long longs to uint64_t to increase readability

### ISSUE THREAD

**Issue by aidanbush** [ElliottSobek/Password-List-Generator#36]
Swapping unsigned long long int, with uint64_t would increase readability

**Comment by ElliottSobek** [comment]
From what I can read about uint64_t vs unsigned long long there seems to be no difference as far as advantage over the other. I believe keeping the same format regarding how all other variable declarations have been made is more important/consistent than reducing a variable declaration by an amount of characters.

If there is an advantage though the change will certainly be reconsidered.

**Comment by aidanbush** [comment]
Generally uint64_t is type defined to be unsigned long long, or unsigned long (depending on word size).
It makes code easier to read, forces a consistent size, and does not increase the line size for no added benefit.
